Dev
temkarus0070/analyticOrderService pull request #3
Opened 2022-01-12 07:05 UTC by temkarus0070

2022-01-12 16:05 UTC, gudun-ku requested changes
Тут очень хорошо. Поправить мелочи, и можно уже будет мержить. Тут особых вопросов к работе нет, кроме вот пожалуй именования методов в тестах. Ну и со Status нужно решить.

2022-01-12 16:05 UTC, gudun-ku commented on src/main/java/org/temkarus0070/analyticorderservice/AnalyticsService.java
> +        final ReadOnlyWindowStore<OrderStatusData, ValueAndTimestamp<OrdersReport>> readyStats = kafkaStreams.store(StoreQueryParameters.fromNameAndType("readyStats",
слишком длинная строка, нужно перенести после =

2022-01-12 16:05 UTC, gudun-ku commented on src/main/java/org/temkarus0070/analyticorderservice/InvalidDatesAtRequestException.java
> +import org.springframework.web.bind.annotation.ExceptionHandler;
Этот импорт не нужен

2022-01-12 16:05 UTC, gudun-ku commented on src/main/java/org/temkarus0070/analyticorderservice/kafkaStream/OrderReportSerde.java
> +
лишние строки нужно удалить

2022-01-12 16:05 UTC, gudun-ku commented on src/main/java/org/temkarus0070/analyticorderservice/kafkaStream/OrderStatusDataSerde.java
> +
Опять пустые строки

2022-01-12 16:05 UTC, gudun-ku commented on src/main/java/org/temkarus0070/analyticorderservice/kafkaStream/OrdersStatsProcessor.java
> +                }, Materialized.<OrderStatusData, OrdersReport, WindowStore<Bytes, byte[]>>as("readyStats").withValueSerde(ordersReportSerde).withKeySerde(orderStatusDataSerde).withRetention(Duration
тут как-то нужно красивенько разбить после .
.withValueSerde...
.withKeySerde

2022-01-12 16:05 UTC, gudun-ku commented on src/main/java/org/temkarus0070/analyticorderservice/models/GoodDTO.java
> +
тут разбежку с интервалами строк устранить, через одну сделай поля если так нравится чтобы отстояли друг от друга

2022-01-12 16:05 UTC, gudun-ku commented on src/main/java/org/temkarus0070/analyticorderservice/models/OrderStatus.java
> +
Пустые строки опять

2022-01-12 16:05 UTC, gudun-ku commented on src/main/java/org/temkarus0070/analyticorderservice/models/OrdersReport.java
> +
Пустые строки

2022-01-12 16:05 UTC, gudun-ku commented on src/main/java/org/temkarus0070/analyticorderservice/models/Status.java
> +public enum Status implements Serializable {
Я не смог навскидку понять, чем этот Status отличается от OrderStatus по сути и зачем он нужен, может одного хватит?

2022-01-12 16:05 UTC, gudun-ku commented on src/test/java/org/temkarus0070/analyticorderservice/tests/KafkaTest.java
> +    void test() {
Придумай тестам имена говорящие за то, что тестируешь.

2022-01-12 16:05 UTC, gudun-ku commented on src/test/java/org/temkarus0070/analyticorderservice/tests/KafkaTest.java
> +            ordersToAnalyze.pipeInput(1L, orderDTO, LocalDateTime.of(2020, Month.JANUARY, 1, 12, 0).atZone(ZoneId.systemDefault()).toInstant());
вот в этих тестах даты теряются в коде, может стоит вынести их в константы

2022-01-12 16:57 UTC, temkarus0070 commented on src/main/java/org/temkarus0070/analyticorderservice/models/Status.java
> +public enum Status implements Serializable {
наверное да, одного хватит

2022-01-12 18:44 UTC, merged

2022-01-13 10:29 UTC, gudun-ku reviewed
Отлично. Если что и поменять, то стоит наверное в GoodDTO и OrderDTO использовать тоже Lombok и убрать все созданные вручную геттеры и сеттеры.